
import { Button } from '@/components/ui/button'
import { FileText, Image as ImageIcon } from 'lucide-react'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { AlgorithmResult } from '@/lib/types'
import type { BracketMethodParams } from './BracketMethodConfig'

interface Props {
  result: AlgorithmResult
  params: BracketMethodParams
  methodId: 'bisection' | 'false-position'
}

export default function ExportActions({ result, params, methodId }: Props) {
  const methodName = methodId === 'bisection' ? 'Bisection Method' : 'False-Position Method'
  const filePrefix = methodId === 'bisection' ? 'bisection' : 'false-position'
  const handleDownloadPDF = () => {
    const doc = new jsPDF()

    // Title
    doc.setFont("helvetica", "bold")
    doc.setFontSize(22)
    doc.setTextColor(24, 24, 27)
    doc.text(`${methodName} Analysis`, 14, 22)

    // Subtitle / Branding
    doc.setFont("helvetica", "normal")
    doc.setFontSize(10)
    doc.setTextColor(113, 113, 122)
    doc.text('Generated by ', 14, 28)
    doc.setTextColor(37, 99, 235)
    doc.textWithLink('Iter.', 37, 28, { url: window.location.origin })
    doc.setTextColor(113, 113, 122)
    doc.text(` | ${new Date().toLocaleString()}`, 45, 28)

    // Separator line
    doc.setDrawColor(228, 228, 231)
    doc.setLineWidth(0.5)
    doc.line(14, 32, 196, 32)

    // Parameters section
    doc.setFont("helvetica", "bold")
    doc.setFontSize(12)
    doc.setTextColor(24, 24, 27)
    doc.text('Input Parameters', 14, 42)

    doc.setFont("helvetica", "normal")
    doc.setFontSize(11)
    doc.setTextColor(63, 63, 70)
    doc.text(`Function: f(x) = ${params.funcStr}`, 14, 50)
    doc.text(`Interval: [${params.aStr}, ${params.bStr}]`, 14, 56)
    doc.text(`Tolerance: ${params.toleranceStr}`, 14, 62)

    // Results section
    doc.setFont("helvetica", "bold")
    doc.setTextColor(24, 24, 27)
    doc.text('Final Result', 100, 42)

    doc.setFont("helvetica", "normal")
    doc.setTextColor(63, 63, 70)
    doc.text(`Estimated Root: ${result.root !== null ? result.root.toPrecision(8) : 'N/A'}`, 100, 50)
    doc.text(`Total Iterations: ${result.totalIterations}`, 100, 56)
    doc.text(`Final Error: ${result.finalError.toExponential(4)}`, 100, 62)

    const tableData = result.iterations.map(i => [
      i.iteration,
      i.a.toPrecision(8),
      i.b.toPrecision(8),
      i.c.toPrecision(8),
      i.fc.toExponential(4),
      i.error.toExponential(4)
    ])

    autoTable(doc, {
      startY: 72,
      head: [['Iter', 'a', 'b', 'c', 'f(c)', 'Error']],
      body: tableData,
      theme: 'grid',
      styles: { font: 'courier', fontSize: 9, textColor: [39, 39, 42] },
      headStyles: { fillColor: [24, 24, 27], textColor: [255, 255, 255], font: 'helvetica', fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [250, 250, 250] }
    })

    doc.save(`${filePrefix}-results-${Date.now()}.pdf`)
  }

  const handleDownloadGraph = () => {
    // We target the function plot div
    const el = document.getElementById('function-plot') as any
    if (el) {
      // @ts-ignore
      import('plotly.js-dist-min').then(Plotly => {
        Plotly.default.downloadImage(el, { format: 'png', width: 800, height: 600, filename: `${filePrefix}-graph-${Date.now()}` })
      }).catch(err => console.error("Failed to export graph", err))
    }
  }

  return (
    <div className="flex flex-wrap items-center gap-3">
      <Button variant="outline" size="sm" onClick={handleDownloadPDF} className="bg-white">
        <FileText className="w-4 h-4 mr-2" />
        Download PDF
      </Button>
      <Button variant="outline" size="sm" onClick={handleDownloadGraph} className="bg-white">
        <ImageIcon className="w-4 h-4 mr-2" />
        Download Graph
      </Button>
    </div>
  )
}
